# Exon Inclusion Analysis

In [ ]:
!pip install ipykernel
!python -m ipykernel install --user --name finalproject --display-name "Python (final project)"

Requirement already satisfied: ipykernel in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (7.1.0)
Requirement already satisfied: comm>=0.1.1 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipykernel) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipykernel) (1.8.17)
Requirement already satisfied: ipython>=7.23.1 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipykernel) (9.6.0)
Requirement already satisfied: jupyter-client>=8.0.0 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipykernel) (8.6.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipykernel) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipykernel) (0.2.1)
Requirement already satisfied: nest-asyncio>=1.4 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipykernel) (1.6.0)
Requirement already satisfied: packaging>=22 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipykernel) (25.0)
Requirement already satisfied: psutil>=5.7 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipykernel) (7.1.3)
Requirement already satisfied: pyzmq>=25 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipykernel) (27.1.0)
Requirement already satisfied: tornado>=6.2 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipykernel) (6.5.2)
Requirement already satisfied: traitlets>=5.4.0 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipykernel) (5.14.3)
Requirement already satisfied: decorator in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel) (1.1.1)
Requirement already satisfied: jedi>=0.16 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel) (0.19.2)
Requirement already satisfied: pexpect>4.3 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel) (2.19.2)
Requirement already satisfied: stack_data in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel) (0.6.3)
Requirement already satisfied: typing_extensions>=4.6 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel) (4.15.0)
Requirement already satisfied: wcwidth in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel) (0.2.14)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel) (0.8.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from jupyter-client>=8.0.0->ipykernel) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel) (4.5.0)
Requirement already satisfied: ptyprocess>=0.5 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from pexpect>4.3->ipython>=7.23.1->ipykernel) (0.7.0)
Requirement already satisfied: six>=1.5 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from python-dateutil>=2.8.2->jupyter-client>=8.0.0->ipykernel) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from stack_data->ipython>=7.23.1->ipykernel) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from stack_data->ipython>=7.23.1->ipykernel) (3.0.0)
Requirement already satisfied: pure_eval in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from stack_data->ipython>=7.23.1->ipykernel) (0.2.3)
Installed kernelspec finalproject in /home/biouser/.local/share/jupyter/kernels/finalproject

In [ ]:
## 0. Setup
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
from scipy.stats import spearmanr, bootstrap
from gtfparse import read_gtf
import pysam  
from matplotlib.colors import LinearSegmentedColormap
from functions import (
    load_type_neurons,
    compute_spearman_corr,
    clean_names,
    spearman_corr_labels,
)

## 1. Load Data
- Load `altExonUsage_devel_type.gz`
- Filter only column with `Neuron` 
- Combine `Exon` and `Gene` to `GE` (`Exon::Gene`)

In [ ]:
type_neurons = load_type_neurons("../../data/altExonUsage_devel_type.gz")
type_neurons.head(20)

,P14_Hippocampus_ExciteNeuron,P14_Hippocampus_InhibNeuron,P14_VisCortex_ExciteNeuron,P14_VisCortex_InhibNeuron,P21_Hippocampus_ExciteNeuron,P21_Hippocampus_InhibNeuron,P21_VisCortex_ExciteNeuron,P21_VisCortex_InhibNeuron,P28_Hippocampus_ExciteNeuron,P28_Hippocampus_InhibNeuron,P28_VisCortex_ExciteNeuron,P28_VisCortex_InhibNeuron,P56_Hippocampus_ExciteNeuron,P56_Hippocampus_InhibNeuron,P56_VisCortex_ExciteNeuron,P56_VisCortex_InhibNeuron
GE,,,,,,,,,,,,,,,,
chr1_162273620_162273649_-::ENSMUSG00000040265.16,0.032520,0.000000,0.008152,0.000000,0.049351,0.024000,0.000000,0.000000,0.015544,0.007812,0.001163,0.000000,0.015831,0.026316,0.005181,0.001821
chr1_186690721_186690804_-::ENSMUSG00000039239.14,0.000000,NaN,NaN,NaN,0.075472,NaN,NaN,NaN,0.083333,NaN,NaN,NaN,0.139073,NaN,0.019608,0.125000
chr1_172286198_172286396_-::ENSMUSG00000007097.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.818182,NaN
chr1_83384894_83384972_-::ENSMUSG00000026163.17,0.608364,0.642140,0.707604,0.657718,0.631307,0.707113,0.767779,0.776471,0.670919,0.666667,0.789824,0.805970,0.641826,0.694915,0.781662,0.712150
chr1_172279313_172279467_-::ENSMUSG00000007097.14,1.000000,NaN,1.000000,NaN,0.823529,NaN,0.823529,NaN,1.000000,NaN,1.000000,NaN,1.000000,NaN,0.965517,NaN
chr1_163253977_163254048_-::ENSMUSG00000026586.16,0.545455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
chr1_172287200_172287468_-::ENSMUSG00000007097.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
chr1_16486020_16486150_-::ENSMUSG00000025920.19,0.204724,0.032967,0.240229,0.097222,0.222116,0.230769,0.275465,0.102564,0.223958,0.000000,0.230177,0.132075,0.218418,0.050633,0.220895,0.145867
chr1_162675605_162675841_-::ENSMUSG00000040225.15,0.812834,0.714286,0.824022,0.848485,0.891247,0.795455,0.818493,0.914286,0.869822,1.000000,0.841040,NaN,0.950530,0.840000,0.900850,0.959184
chr1_30837105_30837266_-::ENSMUSG00000048874.15,0.159420,0.082569,0.141469,0.195122,0.148862,0.163043,0.153000,0.217391,0.192575,0.172414,0.170354,0.205882,0.128942,0.253333,0.183346,0.246057
chr1_69685694_69685797_-::ENSMUSG00000025997.13,0.076923,0.214286,0.016949,NaN,0.089109,0.071429,0.020408,NaN,0.033333,0.000000,0.111111,NaN,0.036145,NaN,0.090909,0.133333
chr1_172285654_172285788_-::ENSMUSG00000007097.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
chr1_135426931_135427041_-::ENSMUSG00000041879.13,0.000000,NaN,0.058824,0.142857,0.156463,0.083333,0.139706,NaN,0.030769,NaN,0.111801,NaN,NaN,NaN,0.129584,0.261905
chr1_58420121_58420211_-::ENSMUSG00000026034.17,0.574468,0.745098,0.690909,NaN,0.711864,0.912281,0.615385,NaN,0.931034,0.909091,0.977778,0.916667,0.813953,0.961538,0.545994,0.775000
chr1_119765878_119765922_-::ENSMUSG00000026384.13,NaN,NaN,1.000000,NaN,0.863636,0.814815,0.861314,0.769231,0.937500,NaN,0.875000,1.000000,1.000000,NaN,0.831818,0.844961
chr1_24030742_24030896_-::ENSMUSG00000026153.15,NaN,NaN,NaN,NaN,0.783333,NaN,0.642857,NaN,1.000000,NaN,1.000000,NaN,1.000000,NaN,0.870130,0.840000
chr1_42663556_42663602_-::ENSMUSG00000060424.14,0.313793,0.322222,0.341404,0.342593,0.353125,0.354167,0.423520,0.370968,0.304668,0.275862,0.426385,0.526316,0.388466,0.400000,0.439563,0.340741
chr1_172280569_172280705_-::ENSMUSG00000007097.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.920000,NaN
chr1_175066617_175066694_-::ENSMUSG00000026527.13,0.342466,0.071429,0.288608,0.115385,0.347561,0.578947,0.388889,NaN,0.302083,0.038462,0.457604,NaN,0.454737,0.200000,0.483698,0.287500
chr1_84795690_84795815_-::ENSMUSG00000026219.14,0.288591,0.472222,0.331536,0.444444,0.320594,0.327273,0.362587,0.466667,0.322695,0.523810,0.380399,0.363636,0.278626,0.428571,0.391031,0.355769

## 2. Performn pairwise Correlation

#### Process data for Spearman correlation
- Remove rows with missing data `NaN`
- Compute Spearman correlation matrix

In [ ]:
corr = compute_spearman_corr(type_neurons)
CN = clean_names(corr)
CN

,P14_HIPP_Excite,P14_HIPP_Inhib,P14_VIS_Excite,P14_VIS_Inhib,P21_HIPP_Excite,P21_HIPP_Inhib,P21_VIS_Excite,P21_VIS_Inhib,P28_HIPP_Excite,P28_HIPP_Inhib,P28_VIS_Excite,P28_VIS_Inhib,P56_HIPP_Excite,P56_HIPP_Inhib,P56_VIS_Excite,P56_VIS_Inhib
P14_HIPP_Excite,1.000000,0.865320,0.909911,0.886845,0.853609,0.841284,0.821143,0.845471,0.849383,0.841355,0.851881,0.817556,0.891090,0.885976,0.828041,0.816164
P14_HIPP_Inhib,0.865320,1.000000,0.852621,0.899736,0.843048,0.884450,0.814208,0.847335,0.830215,0.866666,0.819943,0.838889,0.836201,0.896754,0.813307,0.869893
P14_VIS_Excite,0.909911,0.852621,1.000000,0.910102,0.830537,0.830371,0.810601,0.866398,0.828769,0.833890,0.855997,0.821240,0.882145,0.870460,0.833206,0.823089
P14_VIS_Inhib,0.886845,0.899736,0.910102,1.000000,0.877425,0.881019,0.870836,0.886242,0.856335,0.864176,0.869230,0.900208,0.861776,0.893214,0.864582,0.898332
P21_HIPP_Excite,0.853609,0.843048,0.830537,0.877425,1.000000,0.861511,0.813749,0.879860,0.766540,0.811592,0.726914,0.761101,0.821703,0.885722,0.807427,0.833759
P21_HIPP_Inhib,0.841284,0.884450,0.830371,0.881019,0.861511,1.000000,0.844983,0.901320,0.825075,0.878993,0.811337,0.875430,0.825536,0.896380,0.837813,0.890832
P21_VIS_Excite,0.821143,0.814208,0.810601,0.870836,0.813749,0.844983,1.000000,0.889425,0.728493,0.789257,0.724341,0.785212,0.787906,0.869884,0.830261,0.819163
P21_VIS_Inhib,0.845471,0.847335,0.866398,0.886242,0.879860,0.901320,0.889425,1.000000,0.849540,0.847341,0.861349,0.902924,0.855445,0.882308,0.880106,0.913320
P28_HIPP_Excite,0.849383,0.830215,0.828769,0.856335,0.766540,0.825075,0.728493,0.849540,1.000000,0.840163,0.814149,0.816738,0.863503,0.884956,0.749237,0.770761
P28_HIPP_Inhib,0.841355,0.866666,0.833890,0.864176,0.811592,0.878993,0.789257,0.847341,0.840163,1.000000,0.827930,0.871407,0.805134,0.885399,0.803124,0.851962
P28_VIS_Excite,0.851881,0.819943,0.855997,0.869230,0.726914,0.811337,0.724341,0.861349,0.814149,0.827930,1.000000,0.805953,0.857559,0.888516,0.757648,0.764599
P28_VIS_Inhib,0.817556,0.838889,0.821240,0.900208,0.761101,0.875430,0.785212,0.902924,0.816738,0.871407,0.805953,1.000000,0.814282,0.889349,0.779791,0.835272
P56_HIPP_Excite,0.891090,0.836201,0.882145,0.861776,0.821703,0.825536,0.787906,0.855445,0.863503,0.805134,0.857559,0.814282,1.000000,0.916052,0.839669,0.815281
P56_HIPP_Inhib,0.885976,0.896754,0.870460,0.893214,0.885722,0.896380,0.869884,0.882308,0.884956,0.885399,0.888516,0.889349,0.916052,1.000000,0.885857,0.915217
P56_VIS_Excite,0.828041,0.813307,0.833206,0.864582,0.807427,0.837813,0.830261,0.880106,0.749237,0.803124,0.757648,0.779791,0.839669,0.885857,1.000000,0.873057
P56_VIS_Inhib,0.816164,0.869893,0.823089,0.898332,0.833759,0.890832,0.819163,0.913320,0.770761,0.851962,0.764599,0.835272,0.815281,0.915217,0.873057,1.000000

In [ ]:
f4a_labels = spearman_corr_labels(CN)

NameError: name 'cnn' is not defined