# Exon Inclusion Analysis

In [1]:
!pip install ipykernel
!python -m ipykernel install --user --name finalproject --display-name "Python (final project)"

Requirement already satisfied: ipykernel in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (7.1.0)
Requirement already satisfied: comm>=0.1.1 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipykernel) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipykernel) (1.8.17)
Requirement already satisfied: ipython>=7.23.1 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipykernel) (9.6.0)
Requirement already satisfied: jupyter-client>=8.0.0 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipykernel) (8.6.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipykernel) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipykernel) (0.2.1)
Requirement already satisfied: nest-asyncio>=1.4 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipykernel) (1.6.0)
Requirement already satisfied: packaging>=22 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipykernel) (25.0)
Requirement already satisfied: psutil>=5.7 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipykernel) (7.1.3)
Requirement already satisfied: pyzmq>=25 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipykernel) (27.1.0)
Requirement already satisfied: tornado>=6.2 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipykernel) (6.5.2)
Requirement already satisfied: traitlets>=5.4.0 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipykernel) (5.14.3)
Requirement already satisfied: decorator in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel) (1.1.1)
Requirement already satisfied: jedi>=0.16 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel) (0.19.2)
Requirement already satisfied: pexpect>4.3 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel) (2.19.2)
Requirement already satisfied: stack_data in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel) (0.6.3)
Requirement already satisfied: typing_extensions>=4.6 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel) (4.15.0)
Requirement already satisfied: wcwidth in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel) (0.2.14)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel) (0.8.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from jupyter-client>=8.0.0->ipykernel) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel) (4.5.0)
Requirement already satisfied: ptyprocess>=0.5 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from pexpect>4.3->ipython>=7.23.1->ipykernel) (0.7.0)
Requirement already satisfied: six>=1.5 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from python-dateutil>=2.8.2->jupyter-client>=8.0.0->ipykernel) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from stack_data->ipython>=7.23.1->ipykernel) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from stack_data->ipython>=7.23.1->ipykernel) (3.0.0)
Requirement already satisfied: pure_eval in /home/biouser/miniconda3/envs/bioinfo/lib/python3.11/site-packages (from stack_data->ipython>=7.23.1->ipykernel) (0.2.3)
Installed kernelspec finalproject in /home/biouser/.local/share/jupyter/kernels/finalproject

In [10]:
## 0. Setup
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
from scipy.stats import spearmanr, bootstrap
from gtfparse import read_gtf
import pysam  
from matplotlib.colors import LinearSegmentedColormap
from functions import (
    load_type_neurons
)

In [3]:
type_alt = pd.read_table('../../data/altExonUsage_devel_type.gz', sep='\t', compression='gzip')
type_alt.shape

(8962, 34)

In [8]:
type_alt.tail(15)

,Exon,Gene,P14_Hippocampus_Astro,P14_Hippocampus_Oligo,P14_Hippocampus_ExciteNeuron,P14_Hippocampus_InhibNeuron,P14_VisCortex_Astro,P14_VisCortex_Oligo,P14_VisCortex_ExciteNeuron,P14_VisCortex_InhibNeuron,...,P28_VisCortex_ExciteNeuron,P28_VisCortex_InhibNeuron,P56_Hippocampus_Astro,P56_Hippocampus_Oligo,P56_Hippocampus_ExciteNeuron,P56_Hippocampus_InhibNeuron,P56_VisCortex_Astro,P56_VisCortex_Oligo,P56_VisCortex_ExciteNeuron,P56_VisCortex_InhibNeuron
8947,chr16_93597361_93597420_-,ENSMUSG00000022948.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.333333,NaN
8948,chr16_96190194_96190229_-,ENSMUSG00000045275.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.500000,NaN
8949,chr16_14111545_14111771_-,ENSMUSG00000060657.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.935484,NaN
8950,chr17_46539253_46539388_-,ENSMUSG00000040327.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.727273,NaN
8951,chr17_34847408_34847461_-,ENSMUSG00000040356.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.727273,NaN
8952,chr17_32381084_32381156_-,ENSMUSG00000024050.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.153846,NaN
8953,chr17_56884751_56884968_+,ENSMUSG00000024209.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.411765,NaN
8954,chr17_35235488_35235558_+,ENSMUSG00000024403.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.400000,NaN
8955,chr18_34584214_34584285_-,ENSMUSG00000049357.11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.333333,NaN
8956,chr18_12190960_12191023_+,ENSMUSG00000024410.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.250000,NaN
8957,chr19_47488206_47488311_-,ENSMUSG00000042694.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.238095,NaN
8958,chrX_12136401_12137200_-,ENSMUSG00000040363.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.636364,NaN
8959,chrX_36758855_36759010_+,ENSMUSG00000037636.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.230769,NaN
8960,chrX_100611748_100611947_+,ENSMUSG00000060890.11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.761905,NaN
8961,chrX_74143446_74143685_+,ENSMUSG00000031394.11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.714286,NaN

In [13]:
type_neurons = load_type_neurons("../../data/altExonUsage_devel_type.gz")
type_neurons.head(10)

,P14_Hippocampus_ExciteNeuron,P14_Hippocampus_InhibNeuron,P14_VisCortex_ExciteNeuron,P14_VisCortex_InhibNeuron,P21_Hippocampus_ExciteNeuron,P21_Hippocampus_InhibNeuron,P21_VisCortex_ExciteNeuron,P21_VisCortex_InhibNeuron,P28_Hippocampus_ExciteNeuron,P28_Hippocampus_InhibNeuron,P28_VisCortex_ExciteNeuron,P28_VisCortex_InhibNeuron,P56_Hippocampus_ExciteNeuron,P56_Hippocampus_InhibNeuron,P56_VisCortex_ExciteNeuron,P56_VisCortex_InhibNeuron
GE,,,,,,,,,,,,,,,,
chr1_162273620_162273649_-::ENSMUSG00000040265.16,0.032520,0.000000,0.008152,0.000000,0.049351,0.024000,0.000000,0.000000,0.015544,0.007812,0.001163,0.000000,0.015831,0.026316,0.005181,0.001821
chr1_186690721_186690804_-::ENSMUSG00000039239.14,0.000000,NaN,NaN,NaN,0.075472,NaN,NaN,NaN,0.083333,NaN,NaN,NaN,0.139073,NaN,0.019608,0.125000
chr1_172286198_172286396_-::ENSMUSG00000007097.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.818182,NaN
chr1_83384894_83384972_-::ENSMUSG00000026163.17,0.608364,0.642140,0.707604,0.657718,0.631307,0.707113,0.767779,0.776471,0.670919,0.666667,0.789824,0.805970,0.641826,0.694915,0.781662,0.712150
chr1_172279313_172279467_-::ENSMUSG00000007097.14,1.000000,NaN,1.000000,NaN,0.823529,NaN,0.823529,NaN,1.000000,NaN,1.000000,NaN,1.000000,NaN,0.965517,NaN
chr1_163253977_163254048_-::ENSMUSG00000026586.16,0.545455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
chr1_172287200_172287468_-::ENSMUSG00000007097.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
chr1_16486020_16486150_-::ENSMUSG00000025920.19,0.204724,0.032967,0.240229,0.097222,0.222116,0.230769,0.275465,0.102564,0.223958,0.000000,0.230177,0.132075,0.218418,0.050633,0.220895,0.145867
chr1_162675605_162675841_-::ENSMUSG00000040225.15,0.812834,0.714286,0.824022,0.848485,0.891247,0.795455,0.818493,0.914286,0.869822,1.000000,0.841040,NaN,0.950530,0.840000,0.900850,0.959184
chr1_30837105_30837266_-::ENSMUSG00000048874.15,0.159420,0.082569,0.141469,0.195122,0.148862,0.163043,0.153000,0.217391,0.192575,0.172414,0.170354,0.205882,0.128942,0.253333,0.183346,0.246057